### ISSUE TITLE
Le tapis roulant du magasin Camp Nord envoi droit dans le vide VERS UNE MORT CERTAINE si on sort en fin de parcours

### ISSUE THREAD

**Issue by SarukaUsagi** [arnaudhuc/SaveGames#1]
**Comportement observé :**
En sortant du tapis longeant le magasin on est projeté dans le vide 💀

**Comportement attendu :** 
Un mur de sécurité permet au client de rester dans le centre commercial.
Aucun client ne meurt en faisant ses courses.

**Comment by Altaric** [comment]
Si le client n'est pas capable de lire le manuel et qu'il tient à SAUTER du tapis, qu'il aille en ENFER! (littéralement)

**Comment by SarukaUsagi** [comment]
Le manuel n'a pas été validé par le comité de validation des manuels. Le mur de sécurité est toujours requis.
De plus considérant la situation actuelle, il convient de favoriser exclusivement les modalités de bon sens, pour le futur.

**Comment by Tesclosh** [comment]
C'est plus un problème d'ergonomie du système que de manuel : les clients ne vont jamais lire les manuels de toute façon ! En solution alternative au mur (mur qui pourrait frustrer le client), on peut peut être mettre un jumper directionnel à la place, pour permettre au client de re-visiter le magasin une deuxieme fois s'il atteint la limite.

**Comment by SarukaUsagi** [comment]
Un mur de jumper ?
On se rapproche de quelque chose là !
De plus, dans le cas particulier de l'inertie que nous constatons, il faut comprendre la globalité des alternatives envisageables, avec toute la prudence requise.

**Comment by chaurunda** [comment]
J'ai l'impression que la demande prend du retard . Nous allons devoir agir avec rapidité si nous ne souhaitons pas subir les agios comme indiqué dans le manuel d'installation du tapis, alinéa 37.
